### ISSUE TITLE
Consider payment options beyond donations

### ISSUE THREAD

**Issue by curtcox** [adamcohenhillel/ADeus#13]
Some people will be more willing to pay for something than donate. 
I would like to have an option where I paid more in exchange for doing less work.
That includes acquisition of hardware, installation of software, and maintenance of software. 

If you didn't want to do this, would you be comfortable with someone else doing it?
Would you be willing to link to them in the readme?

**Comment by adamcohenhillel** [comment]
Hey,I agree! and I will definitely get to that once I set up the Raspberry Pi Zero and the bluetooth pairing

Also, would love to get some help there, happy to collab, if you keen!

**Comment by curtcox** [comment]
I'm keen. Now I need to see if I'm capable. I'll start looking things over.

**Comment by adamcohenhillel** [comment]
discussion moved to discord - https://discord.gg/q4vGyfmk
