### ISSUE TITLE
Adeus brand identity design 

### ISSUE THREAD

**Issue by ayoolafelix** [adamcohenhillel/ADeus#14]
Designing an identity for the first open source AI wearable device. This identity should include the logo, an identity system, app icon, epehemerals, social media post templates.

**Comment by adamcohenhillel** [comment]
I would love help with that!

**Comment by ayoolafelix** [comment]
Me too hence why I created the issue. My handle is @ayoolafelix on twitter let’s talk and see how we can approach it

**Comment by Jacksonmills** [comment]
https://ui.jln.dev/theme/kytqTWsE4kvKWAdk

I worked on some basic color themes that played off the adeusRegular green in the codebase, even if we don't use that green this is a solid foundation LMK how you like it!

![image](https://github.com/adamcohenhillel/ADeus/assets/19780885/687c2ad8-fb6a-4154-92b1-b75c4d332fc5)
![image](https://github.com/adamcohenhillel/ADeus/assets/19780885/599562b4-9a0a-4862-bef3-7c432ba787ef)

**Comment by Jacksonmills** [comment]
Also more on topic I would love to help in anyway for brand/creative 🫡✨

**Comment by adamcohenhillel** [comment]
moved to discord
