### ISSUE TITLE
Make the menu Items minimizable 

### ISSUE THREAD

**Issue by adamcohenhillel** [adamcohenhillel/ADeus#29]
Seems like we will have growing menu items, and stuff like that.

Probably need to implement some kind of menu Items minimizable.

Found some cool examples

https://codesandbox.io/p/sandbox/framer-motion-side-menu-mx2rw

https://github.com/adamcohenhillel/ADeus/assets/633840/a5e5bfd8-1f6e-40d0-8a0f-9ed169fcad97

**Comment by adamcohenhillel** [comment]
@Jacksonmills

**Comment by Jacksonmills** [comment]
https://github.com/adamcohenhillel/ADeus/pull/32
