### ISSUE TITLE
400 The audio file could not be decoded or its format is not supported.

### ISSUE THREAD

**Issue by leeeboo** [adamcohenhillel/ADeus#60]
I got '400 The audio file could not be decoded or its format is not supported.' from logs.'
I test the program:
1.python_recorder_client on my local macbook record a good audio can playback by quicktime and post to supabase function got a success response from OpenAI API
2.The audio which recoded by coralai board ' s format is invalid. Can not play by quicktime and got '400 The audio file could not be decoded or its format is not supported.' from OpenAI API

**Comment by leeeboo** [comment]
[audio_1708322352195537000.wav.zip](https://github.com/adamcohenhillel/ADeus/files/14327074/audio_1708322352195537000.wav.zip)
here is a bad audio

**Comment by leeeboo** [comment]
Yes. It recorded by the program which flash into the coralai board. I did
not make any changes.


krislyy ***@***.***>于2024年2月19日 周一20:50写道：

**Comment by makeiteasierapps** [comment]
The PR to resolve this should be approved shortly
