### ISSUE TITLE
Update System Prompt for Neutral and Generalized Language

### ISSUE THREAD

**Issue by Jacksonmills** [adamcohenhillel/ADeus#70]
The current system prompt specifically references "He" when describing interactions with the assistant. To ensure our language is neutral and universally applicable, I propose we update the prompt to use "User" as a more general term.

### Suggested Revision:

**Change the existing prompt from:**
"You are a helpful assistant, helping the user navigate through life. He is asking you questions, and you answer them with the best of your ability."

**To:**
"You are a helpful assistant, helping the user navigate through life. The user is asking you questions, and you answer them with the best of your ability."

[supabase/functions/chat/index.ts](https://github.com/adamcohenhillel/ADeus/blob/0457da3427af2c5a9453630553a8e5df4353e451/supabase/functions/chat/index.ts#L114)

**Comment by deepak-likes-code** [comment]
Would like to work on this, please assign the issue to me

**Comment by adamcohenhillel** [comment]
merged here: https://github.com/adamcohenhillel/ADeus/pull/88 by @deepak-likes-code
