### ISSUE TITLE
Question: Future of this repository with implications of Open Interpreter

### ISSUE THREAD

**Issue by colemvnio** [adamcohenhillel/ADeus#98]
This is directed more at the owner of the repository;

Do you plan on maintaining and and supporting this repository/project even with your implications in a [direct alternative/competitor](https://www.openinterpreter.com/01)

Thank you;

**Comment by adamcohenhillel** [comment]
hey @colemvnio - planning on supporting this repo yeah. I am currently no part of 01 (was there before ADeus started)
